{
  "hash": "89b3d0d3f88affc2bbf5cf998b24280a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Project 2\"\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidycensus\", repos = \"https://cloud.r-project.org\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe downloaded binary packages are in\n\t/var/folders/m0/q7ycmxr14311yyb1w1lfh5680000gn/T//RtmpnQZy7U/downloaded_packages\n```\n\n\n:::\n\n```{.r .cell-code}\ninstall.packages(\"purrr\", repos = \"https://cloud.r-project.org\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe downloaded binary packages are in\n\t/var/folders/m0/q7ycmxr14311yyb1w1lfh5680000gn/T//RtmpnQZy7U/downloaded_packages\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidycensus)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.2.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_api_key(\"dcff66db10ae72ca67f1225694d5f11468367056\", install = TRUE,overwrite=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nYour original .Renviron will be backed up and stored in your R HOME directory if needed.\nYour API key has been stored in your .Renviron and can be accessed by Sys.getenv(\"CENSUS_API_KEY\"). \nTo use now, restart R or run `readRenviron(\"~/.Renviron\")`\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"dcff66db10ae72ca67f1225694d5f11468367056\"\n```\n\n\n:::\n:::\n\n\nPart 1\n1. Choose a question to investigate. Describe what is the question you aim to answer with the data and what you want to visualize.\n\nI want find out number of Filipinos and Chinese in the US. \nI also want the distribution of male vs female in the Asian population\n\n2. Extract data from the tidycensus API. Use at least three different calls to the tidycensus API to extract out different datasets. For example, these could be across years, locations, or variables.\n\nI RECEIVED CODE AND DEBUGGING HELP FROM CHAT GPT .\n\n::: {.cell}\n\n```{.r .cell-code}\n# Total counts from detailed race tables 2023\ncount_2023 <- get_acs(\n  geography = \"us\",\n  table = \"B02015\",\n  year = 2023,\n  survey = \"acs1\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nGetting data from the 2023 1-year ACS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe 1-year ACS provides data for geographies with populations of 65,000 and greater.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading ACS1 variables for 2023 from table B02015. To cache this dataset for faster access to ACS tables in the future, run this function with `cache_table = TRUE`. You only need to do this once per ACS dataset.\n```\n\n\n:::\n\n```{.r .cell-code}\n#Counts 2011\ncount_2011 <- get_acs(\n  geography = \"us\",\n  table = \"B02015\",\n  year = 2011,\n  survey = \"acs1\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nGetting data from the 2011 1-year ACS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe 1-year ACS provides data for geographies with populations of 65,000 and greater.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading ACS1 variables for 2011 from table B02015. To cache this dataset for faster access to ACS tables in the future, run this function with `cache_table = TRUE`. You only need to do this once per ACS dataset.\n```\n\n\n:::\n\n```{.r .cell-code}\n#Age, Sex 2022 (5 years)\nage_sex_2022 <- get_acs(\n  geography = \"us\",\n  table = \"B01001D\", \n  year = 2022, \n  survey = \"acs5\", \n  cache_table = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nGetting data from the 2018-2022 5-year ACS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading ACS5 variables for 2022 from table B01001D and caching the dataset for faster future access.\n```\n\n\n:::\n:::\n\n\n3. Clean the data. Include some form of data wrangling and data visualization using packages such as dplyr or tidyr. Other packages that might be helpful to you include lubridate, stringr, and forcats. You must use at least two functions from purrr.\n\nWe first look at the counts of Chinese and Filipinos in the US. \n\n::: {.cell}\n\n```{.r .cell-code}\n#Combines count_2011 and count_2023\nall_counts <- bind_rows(\n  mutate(count_2023, year = 2023),\n  mutate(count_2011, year = 2011)\n)\n\n#Filters to only include Filipinos and Chinese\nasian_counts <- all_counts %>%\n  filter(str_detect(variable, \"B02015_008|B02015_007|B02015_008E|B02015_007E\")) %>%\n  mutate(\n    race = case_when(\n      str_detect(variable, \"B02015_008|B02015_008E\") ~ \"Filipino\",\n      str_detect(variable, \"B02015_007|B02015_007E\") ~ \"Chinese\",\n      TRUE ~ \"Other\"\n    )\n  ) %>%\n  select(NAME, year, race, estimate, moe)\n\n#Summarizes count by race\n#This part of the code was done by chatGPT\nsummary_counts <- asian_counts %>%\n  split(.$race) %>%\n  map_dfr(~ summarise(.x,\n                      total = sum(estimate),\n                      .by = year),\n          .id = \"race\")\n\nprint(summary_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  race      year   total\n  <chr>    <dbl>   <dbl>\n1 Chinese   2023    7674\n2 Chinese   2011 3361879\n3 Filipino  2023  262269\n4 Filipino  2011 2538325\n```\n\n\n:::\n:::\n\nThe graph shows the number of Filipinos and Chinese in 2011 and 2023 respectively. The 2023 data pull is obviously inaccurate, I am unsure why, even after observing the data table. Attempting to use 2024 data resulted in same findings.\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(count_2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 34 × 5\n   GEOID NAME          variable   estimate   moe\n   <chr> <chr>         <chr>         <dbl> <dbl>\n 1 1     United States B02015_001 20052323 46718\n 2 1     United States B02015_002  4228441 52414\n 3 1     United States B02015_003   337925 15696\n 4 1     United States B02015_004   725773 18935\n 5 1     United States B02015_005  1466761 36764\n 6 1     United States B02015_006    39237  7560\n 7 1     United States B02015_007     7674  1822\n 8 1     United States B02015_008   262269 13020\n 9 1     United States B02015_009     1170  1408\n10 1     United States B02015_010   220379 14764\n# ℹ 24 more rows\n```\n\n\n:::\n:::\n\nCode with help from chatGPT. I tried to understand the code and chose this one after vetoing the others. \n\n::: {.cell}\n\n```{.r .cell-code}\nsex_totals_final <- age_sex_2022 %>%\n  filter(variable %in% c(\"B01001D_002\", \"B01001D_017\")) %>%\n  mutate(\n    Sex_Group = if_else(\n      variable == \"B01001D_002\",\n      \"Male\",\n      \"Female\"\n    )\n  ) %>%\n  select(Sex_Group, Estimate = estimate) \n\nprint(sex_totals_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Sex_Group Estimate\n  <chr>        <dbl>\n1 Male       9182713\n2 Female     9930266\n```\n\n\n:::\n\n```{.r .cell-code}\n#Purrr function by chatGPT\ntotal_pop <- sum(sex_totals_final$Estimate)\nsex_totals_with_percent <- sex_totals_final %>%\n  mutate(\n    Percent = map_dbl(\n      .x = Estimate, \n      .f = ~ (.x / total_pop) * 100\n    )\n  )\nprint(sex_totals_with_percent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Sex_Group Estimate Percent\n  <chr>        <dbl>   <dbl>\n1 Male       9182713    48.0\n2 Female     9930266    52.0\n```\n\n\n:::\n:::\n\n4. Visualize the data. Create data visualizations of your choice. However, your analysis should include at least three plots with you using at least two different geom_*() functions from ggplot2 (or another package with geom_*() functions).\n\nwith code help from chat GPT To add labels and prettify the charts\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(summary_counts, aes(x = factor(year), y = total, fill = race)) +\n  geom_col(position = \"dodge\") +\n  geom_text(aes(label = total, y = total + 0),  # just above bar\n            position = position_dodge(width = 0.9)) +\n  labs(x = \"Year\", y = \"Total\", fill = \"Race\", title = \"Counts by Year and Race\")\n```\n\n::: {.cell-output-display}\n![](Project-2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsex_totals_final <- sex_totals_final %>%\n  mutate(perc = Estimate / sum(Estimate) * 100,\n         label = paste0(Sex_Group, \"\\n\", Estimate, \" (\", round(perc, 1), \"%)\"))\n\nggplot(sex_totals_final, aes(x = \"\", y = Estimate, fill = Sex_Group)) +\n  geom_col() +\n  coord_polar(theta = \"y\") +\n  geom_text(aes(label = label, y = cumsum(Estimate) - Estimate/2)) +  # centered on slice\n  labs(fill = \"Sex\", title = \"Sex Distribution\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Project-2_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\nsex_totals_final <- sex_totals_final %>%\n  mutate(label = paste0(Estimate, \" (\", round(Estimate / sum(Estimate) * 100, 1), \"%)\"))\n\nggplot(sex_totals_final, aes(x = \"Asian Population\", y = Estimate, fill = Sex_Group)) +\n  geom_col() +\n  geom_text(aes(label = label, y = cumsum(Estimate) - Estimate/2)) +  # center inside each segment\n  labs(x = \"\", y = \"Population\", fill = \"Sex\", title = \"Asian Population by Sex\")\n```\n\n::: {.cell-output-display}\n![](Project-2_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n:::\n\n\n5. Report your findings. Write up your data analysis as a brief report. The report should be readable by a scientist uninvolved in the study. Think about how you can write a data analysis that is both concise, but also informative. Include a paragraph summarizing your methods and key findings. Include any limitations or potential biases in pulling data from the API or the analysis. Be sure to comment and organize your code so is easy to understand what you are doing and consider including portions of the code in an Appendix, if helpful.\n\nThere were more Chinese than Filipinos in 2011. The data for 2023 was inaccurate, I likely pulled the wrong data from ACS. (Or used the wrong code). There are more women (48%) than men (52%)in the Asian population (100%).\n\nPart 2\n\nIn this part, you will use the rvest package to scrape data from a website, wrangle and analyze the data, and summarize your findings.\n\n1. Choose a website to scrape. \nChosen Website: https://books.toscrape.com/ \n\n2. Extract data with rvest. Here, you will want to identify the specific HTML elements or CSS selectors containing the data. Then, use rvest functions like read_html(), html_elements(), and html_text() or html_table() to retrieve the data.\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"rvest\", repos = \"https://cloud.r-project.org\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe downloaded binary packages are in\n\t/var/folders/m0/q7ycmxr14311yyb1w1lfh5680000gn/T//RtmpnQZy7U/downloaded_packages\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rvest)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'rvest'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:readr':\n\n    guess_encoding\n```\n\n\n:::\n\n```{.r .cell-code}\npage <- read_html(\"https://books.toscrape.com\")\n\nprice <- page %>%\n html_elements(\".price_color\")  %>%\n html_text2()\n\nprint(price)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"£51.77\" \"£53.74\" \"£50.10\" \"£47.82\" \"£54.23\" \"£22.65\" \"£33.34\" \"£17.93\"\n [9] \"£22.60\" \"£52.15\" \"£13.99\" \"£20.66\" \"£17.46\" \"£52.29\" \"£35.02\" \"£57.25\"\n[17] \"£23.88\" \"£37.59\" \"£51.33\" \"£45.17\"\n```\n\n\n:::\n:::\n\n\n3. Clean the data. Next, perform some basic wrangling, such as remove extra whitespace, handle missing values, and convert data types as needed. You might find the functions from dplyr or tidyr useful for any additional transformations, such as renaming columns, filtering rows, or creating new variables.\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_numeric <- as.numeric(substring(price, 2))\nprice_numeric\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 51.77 53.74 50.10 47.82 54.23 22.65 33.34 17.93 22.60 52.15 13.99 20.66\n[13] 17.46 52.29 35.02 57.25 23.88 37.59 51.33 45.17\n```\n\n\n:::\n:::\n\n\n4. Analyze the data. Perform a simple analysis of your choice. For example, you could\n-Count how many times specific words or themes appear.\n-Create a summary statistic (e.g., average rating, job salary, team win percentage).\n-Create a data visualization (e.g., bar chart, histogram) of an interesting metric.\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_price <- mean(price_numeric)\nmin_price <- min(price_numeric)\nmax_price <- max(price_numeric)\n\ncat(\"mean:\", mean_price, \"min:\", min_price, \"max:\", max_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean: 38.0485 min: 13.99 max: 57.25\n```\n\n\n:::\n:::\n\n\n5. Report your findings. Write up your data analysis as a brief report. The report should be designed for a technical audience, such as a technical manager who appreciates the technical details. Think about how you can write a data analysis that is both concise, but also informative. Include a paragraph summarizing your methods and key findings. Include any limitations or potential biases in scraping data or the analysis. Be sure to comment and organize your code so is easy to understand what you are doing.\n\nThe average price of books in the website was 38.05 pounds, with the range falling between 13.99 and 57.25 pounds. \n\nThis is an exercise to practice using rvest and gadget selector, and the website used is also a dummy website for practicing scraping. \n",
    "supporting": [
      "Project-2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}